# Generated by Django 3.1 on 2020-09-01 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('img', models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics')),
                ('location', models.CharField(max_length=125)),
                ('following', models.ManyToManyField(blank=True, related_name='_userprofile_following_+', to='users.UserProfile')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='posts.Post')),
                ('reposted', models.ManyToManyField(blank=True, related_name='reposted', to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
