# Generated by Django 3.1 on 2020-08-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200830_2015'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reposted',
            field=models.ManyToManyField(blank=True, related_name='reposted', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
