# Generated by Django 3.1 on 2020-08-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200830_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_following_+', to='users.UserProfile'),
        ),
    ]
