# Generated by Django 3.1 on 2020-09-13 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_minorcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minorcomment',
            name='main_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minor-comments+', to='comments.comment'),
        ),
    ]
