# Generated by Django 3.1 on 2020-09-13 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20200913_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minorcomment',
            name='main_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minors', to='comments.comment'),
        ),
    ]
