# Generated by Django 3.1 on 2020-09-12 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200901_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostsPhoto',
        ),
    ]
